spring:
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: product-created-events
      properties:
        spring:
          json:
            trusted:
              packages: "com.ribas.andrei.training.udemy.kafka.products.event.common.event"
      emailNotification:
        event:
          productCreatedEvent:
            topicName: "product-created-events-topic"
  main:
    web-application-type: none