#version: "3.8"

networks:
  kafka-net:
    driver: bridge

services:
  kafka-1:
    image: confluentinc/cp-kafka
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - kafka-net
    ports:
      - "9101:9101"
      - "29092:29092"
      - "29093:29093"
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://${HOSTNAME:-localhost}:9092
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: ${HOSTNAME:-localhost}
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka-1:29092,CONTROLLER://kafka-1:29093,PLAINTEXT_HOST://${HOSTNAME:-localhost}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLUSTER_ID: 'Zm8OeE-6QC2JYh0mfgmPsA'
    volumes:
      - /tmp/kafka/docker-compose/volumes/server-1:/bitnami/kafka

  kafka-2:
    image: confluentinc/cp-kafka
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - kafka-net
    ports:
      - "9111:9111"
      - "29192:29092"
      - "29193:29093"
      - "9192:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092,PLAINTEXT_HOST://${HOSTNAME2:-localhost}:9192
      KAFKA_JMX_PORT: 9111
      KAFKA_JMX_HOSTNAME: ${HOSTNAME2:-localhost}
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka-2:29092,CONTROLLER://kafka-2:29093,PLAINTEXT_HOST://${HOSTNAME2:-localhost}:9192
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLUSTER_ID: 'Zm8OeE-6QC2JYh0mfgmPsA'
    volumes:
      - /tmp/kafka/docker-compose/volumes/server-2:/bitnami/kafka

  kafka-3:
    image: confluentinc/cp-kafka
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      - kafka-net
    ports:
      - "9211:9211"
      - "29292:29092"
      - "29293:29093"
      - "9292:9092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:29092,PLAINTEXT_HOST://${HOSTNAME3:-localhost}:9292
      KAFKA_JMX_PORT: 9211
      KAFKA_JMX_HOSTNAME: ${HOSTNAME3:-localhost}
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-1:29093,2@kafka-2:29093,3@kafka-3:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka-3:29092,CONTROLLER://kafka-3:29093,PLAINTEXT_HOST://${HOSTNAME3:-localhost}:9292
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CLUSTER_ID: 'Zm8OeE-6QC2JYh0mfgmPsA'
    volumes:
      - /tmp/kafka/docker-compose/volumes/server-3:/bitnami/kafka

