# random port
server:
  port: 8080

spring:
  config:
    import: classpath:/application-event-common.yaml

  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9192,kafka-3:9292
    producer:
      bootstrap-servers: kafka-1:9092,kafka-2:9192,kafka-3:9292
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      retries: 3
      properties:
        request:
          timeout:
            ms: 30000
        retry:
          backoff:
            ms: 1000

