# random port
server:
  port: 8080

spring:
  config:
    import: classpath:/application-event-common.yaml

  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9192,kafka-3:9292
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer
      retries: 10
      properties:
        reconnect:
          backoff:
            ms: 1000
            max:
              ms: 10000
        request:
          timeout:
            ms: 30000
        retry:
          backoff:
            ms: 1000
